global using MarketPlace.BLL.Interfaces;
global using MarketPlace.BLL.ViewModels;
global using MarketPlace.WEB.ViewModels;
global using MarketPlace.DAL.Entities;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using System.Net;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Mvc.Rendering;